# Generated by Django 4.2.4 on 2023-08-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_subcategory_product_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
