# Generated by Django 4.2.4 on 2023-10-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_category_managers_alter_product_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='color',
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='Red', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.product')),
            ],
            options={
                'verbose_name_plural': 'Product Colors',
            },
        ),
    ]
