# Generated by Django 4.2.4 on 2023-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_remove_productimages_color_productcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorders',
            name='product_status',
            field=models.CharField(choices=[('Process', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Process', max_length=30),
        ),
    ]
