# Generated by Django 4.2.4 on 2023-10-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_alter_cartorders_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
