# Generated by Django 4.2.4 on 2023-11-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_address_city_address_country_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorders',
            name='payment_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
