# Generated by Django 4.2.4 on 2023-11-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_alter_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(default='Red', max_length=10, unique=True),
        ),
    ]
